# Generated by Django 4.2.24 on 2025-09-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pratos/'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/'),
        ),
    ]
