# Generated by Django 4.2.24 on 2025-09-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('preparacao', 'Preparação'), ('transito', 'Trânsito'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='preparacao', max_length=20),
        ),
    ]
